### ISSUE TITLE
android.view.InflateException

### ISSUE THREAD

**Issue by Alexandersch** [PhilJay/CircleDisplay#3]
I have a few reports on this error:

android.view.InflateException: Binary XML file line #97: Error inflating class com.philjay.circledisplay.CircleDisplay

Caused by: java.lang.NoClassDefFoundError: android.animation.ObjectAnimator
at com.philjay.circledisplay.CircleDisplay.init(CircleDisplay.java:128)
at com.philjay.circledisplay.CircleDisplay.<init>(CircleDisplay.java:102)

I figured out that the problem lays with the support library. it does not support the ObjectAnimator for API level 11 and below.

I guess a workaround would be, only animate when API level is above 11.

Is there maybe another fix for this?

**Comment by PhilJay** [comment]
Circle Display only supports Android 3.0 and higher. 
If you want to support lower android versions, you have to remove the animations.

**Comment by Alexandersch** [comment]
Thnx, i'll disable them for Android 2.3.*
